# Generated by Django 2.1.5 on 2019-01-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.PositiveIntegerField(default=0)),
                ('score_2', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('state', models.CharField(choices=[
                 ('NB', 'Not finished'), ('TIE', 'Tie'), ('WIN', 'Win')], default='NB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              parent_link=True, related_name='basketball_info', to='sports_app.Game')),
                ('score_1', models.PositiveIntegerField(default=0)),
                ('q1_1', models.PositiveIntegerField(default=0)),
                ('q2_1', models.PositiveIntegerField(default=0)),
                ('q3_1', models.PositiveIntegerField(default=0)),
                ('q4_1', models.PositiveIntegerField(default=0)),
                ('threepoint_1', models.PositiveIntegerField(default=0)),
                ('twopoint_1', models.PositiveIntegerField(default=0)),
                ('penalty_1', models.PositiveIntegerField(default=0)),
                ('fouls_1', models.PositiveIntegerField(default=0)),
                ('rebound_1', models.PositiveIntegerField(default=0)),
                ('score_2', models.PositiveIntegerField(default=0)),
                ('q1_2', models.PositiveIntegerField(default=0)),
                ('q2_2', models.PositiveIntegerField(default=0)),
                ('q3_2', models.PositiveIntegerField(default=0)),
                ('q4_2', models.PositiveIntegerField(default=0)),
                ('threepoint_2', models.PositiveIntegerField(default=0)),
                ('twopoint_2', models.PositiveIntegerField(default=0)),
                ('penalty_2', models.PositiveIntegerField(default=0)),
                ('fouls_2', models.PositiveIntegerField(default=0)),
                ('rebound_2', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballPlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FootballGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              parent_link=True, related_name='football_info', to='sports_app.Game')),
                ('goals_1', models.PositiveIntegerField(default=0)),
                ('possession_1', models.PositiveIntegerField(default=0)),
                ('shots_1', models.PositiveIntegerField(default=0)),
                ('shots_on_target_1', models.PositiveIntegerField(default=0)),
                ('yellow_cards_1', models.PositiveIntegerField(default=0)),
                ('red_cards_1', models.PositiveIntegerField(default=0)),
                ('corners_1', models.PositiveIntegerField(default=0)),
                ('offsides_1', models.PositiveIntegerField(default=0)),
                ('fouls_1', models.PositiveIntegerField(default=0)),
                ('goals_2', models.PositiveIntegerField(default=0)),
                ('possession_2', models.PositiveIntegerField(default=0)),
                ('shots_2', models.PositiveIntegerField(default=0)),
                ('shots_on_target_2', models.PositiveIntegerField(default=0)),
                ('yellow_cards_2', models.PositiveIntegerField(default=0)),
                ('red_cards_2', models.PositiveIntegerField(default=0)),
                ('corners_2', models.PositiveIntegerField(default=0)),
                ('offsides_2', models.PositiveIntegerField(default=0)),
                ('fouls_2', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FootballPlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameActivity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='activities', to='sports_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='media', to='sports_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[
                 ('FB', 'Football'), ('BB', 'Basketball')], max_length=2)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True,
                                            null=True, upload_to='posts_pictures')),
                ('context', models.TextField()),
                ('state', models.CharField(choices=[
                 ('DR', 'Draft'), ('PB', 'Published'), ('GR', 'Game Related')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.CASCADE, to='sports_app.Game')),
                ('related_posts', models.ManyToManyField(
                    blank=True, related_name='_newspost_related_posts_+', to='sports_app.NewsPost')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[
                 ('FB', 'Football'), ('BB', 'Basketball')], max_length=2)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('nation', models.CharField(max_length=20)),
                ('height', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(upload_to='player_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='seasons', to='sports_app.League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[
                 ('FB', 'Football'), ('BB', 'Basketball')], max_length=2)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True,
                                            null=True, upload_to='team_pictures')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('num_games', models.PositiveIntegerField(default=0)),
                ('num_wins', models.PositiveIntegerField(default=0)),
                ('num_losts', models.PositiveIntegerField(default=0)),
                ('num_points', models.PositiveIntegerField(default=0)),
                ('num_draws', models.PositiveIntegerField(default=0)),
                ('num_gf', models.PositiveIntegerField(default=0)),
                ('num_ga', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='teams', to='sports_app.League')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='players', to='sports_app.Team'),
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='activities', to='sports_app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(
                related_name='games', to='sports_app.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='games', to='sports_app.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='games1', to='sports_app.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='games2', to='sports_app.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='sports_app.Team'),
        ),
        migrations.AddField(
            model_name='footballplayerinfo',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='football_info', to='sports_app.Player'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comments', to='sports_app.NewsPost'),
        ),
        migrations.AddField(
            model_name='basketballplayerinfo',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='basketball_info', to='sports_app.Player'),
        ),
    ]
