# Generated by Django 2.1.5 on 2019-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='sport',
            field=models.CharField(choices=[('FB', 'Football'), ('BB', 'Basketball')], default='FB', max_length=2),
            preserve_default=False,
        ),
    ]
