# Generated by Django 2.1.5 on 2019-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0002_newspost_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='state',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=2),
            preserve_default=False,
        ),
    ]
