# Generated by Django 2.1.5 on 2019-01-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0006_auto_20190115_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(default=None, upload_to='posts_pictures'),
            preserve_default=False,
        ),
    ]
