# Generated by Django 2.1.5 on 2019-01-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0007_newspost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_pictures'),
        ),
    ]
