# Generated by Django 2.1.5 on 2019-01-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0009_basketballplayer_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballplayer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='basketballplayer',
            name='role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='basketballplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_app.Team'),
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='role',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_app.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
