# Generated by Django 2.1.5 on 2019-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190115_1634'),
        ('sports_app', '0011_auto_20190115_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BasketballPlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FootballGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_1', models.PositiveIntegerField(default=0)),
                ('possession_1', models.PositiveIntegerField(default=0)),
                ('shots_1', models.PositiveIntegerField(default=0)),
                ('shots_on_target_1', models.PositiveIntegerField(default=0)),
                ('yellow_cards_1', models.PositiveIntegerField(default=0)),
                ('red_cards_1', models.PositiveIntegerField(default=0)),
                ('corners_1', models.PositiveIntegerField(default=0)),
                ('offsides_1', models.PositiveIntegerField(default=0)),
                ('fouls_1', models.PositiveIntegerField(default=0)),
                ('goals_2', models.PositiveIntegerField(default=0)),
                ('possession_2', models.PositiveIntegerField(default=0)),
                ('shots_2', models.PositiveIntegerField(default=0)),
                ('shots_on_target_2', models.PositiveIntegerField(default=0)),
                ('yellow_cards_2', models.PositiveIntegerField(default=0)),
                ('red_cards_2', models.PositiveIntegerField(default=0)),
                ('corners_2', models.PositiveIntegerField(default=0)),
                ('offsides_2', models.PositiveIntegerField(default=0)),
                ('fouls_2', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.Game')),
            ],
        ),
        migrations.CreateModel(
            name='FootballPlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FB', 'Football'), ('BB', 'Basketball')], max_length=2)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=32)),
                ('picture', models.ImageField(upload_to='player_pictures')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_app.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='basketballplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='footballplayer',
            name='team',
        ),
        migrations.DeleteModel(
            name='BasketballPlayer',
        ),
        migrations.DeleteModel(
            name='FootballPlayer',
        ),
        migrations.AddField(
            model_name='footballplayerinfo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.Player'),
        ),
        migrations.AddField(
            model_name='basketballplayerinfo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports_app.Player'),
        ),
    ]
