# Generated by Django 2.1.5 on 2019-01-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0012_auto_20190115_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballgameinfo',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='sports_app.Game'),
        ),
    ]
