# Generated by Django 2.1.5 on 2019-01-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0013_auto_20190115_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballgameinfo',
            name='game',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='basketball_info', to='sports_app.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footballgameinfo',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='football_info', to='sports_app.Game'),
        ),
    ]
