# Generated by Django 2.1.5 on 2019-01-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0014_auto_20190115_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
