# Generated by Django 2.1.5 on 2019-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0016_auto_20190115_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures'),
        ),
    ]
