# Generated by Django 2.1.5 on 2019-01-15 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0019_auto_20190115_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='sports_app.Team'),
            preserve_default=False,
        ),
    ]
