# Generated by Django 2.1.5 on 2019-01-15 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0021_auto_20190115_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.Game'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='state',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('GR', 'Game Related')], max_length=2),
        ),
    ]
