# Generated by Django 2.1.5 on 2019-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0022_auto_20190116_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='nation',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
