# Generated by Django 2.1.5 on 2019-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0024_auto_20190116_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='year',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='league',
            name='year',
        ),
    ]
