# Generated by Django 2.1.5 on 2019-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0027_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
