# Generated by Django 2.1.5 on 2019-01-17 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0028_auto_20190116_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to='player_pictures'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports_app.League'),
        ),
    ]
