# Generated by Django 2.1.5 on 2019-01-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0029_auto_20190117_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('NB', 'Not begun'), ('TIE', 'Tie'), ('WIN', 'Win')], default='NB', max_length=3),
        ),
    ]
