# Generated by Django 2.1.5 on 2019-01-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0030_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='player_pictures'),
        ),
    ]
