# Generated by Django 2.1.5 on 2019-01-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0033_auto_20190119_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='activate',
            new_name='active',
        ),
    ]
