# Generated by Django 2.1.5 on 2019-01-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0034_auto_20190119_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('NB', 'Not finished'), ('TIE', 'Tie'), ('WIN', 'Win')], default='NB', max_length=3),
        ),
        migrations.AddField(
            model_name='media',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='sports_app.Game'),
        ),
    ]
