# Generated by Django 2.1.5 on 2019-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0036_auto_20190125_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballgameinfo',
            name='fouls_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='fouls_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='penalty_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='penalty_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q1_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q1_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q2_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q2_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q3_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q3_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q4_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='q4_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='rebound_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='rebound_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='score_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='score_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='threepoint_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='threepoint_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='twopoint_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basketballgameinfo',
            name='twopoint_2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
