# Generated by Django 2.1.5 on 2019-01-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bla',
        ),
    ]
