# Generated by Django 2.1.5 on 2019-01-15 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0009_basketballplayer_game'),
        ('accounts', '0003_remove_user_bla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketball_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.BasketballPlayer')),
                ('football_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.FootballPlayer')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.Game')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
