# Generated by Django 2.1.5 on 2019-01-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='basketball_player',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='football_player',
        ),
    ]
