# Generated by Django 2.1.5 on 2019-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports_app', '0012_auto_20190115_1634'),
        ('accounts', '0005_auto_20190115_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports_app.Player'),
        ),
    ]
